name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change this if your default branch is not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site artifact
        run: |
          mkdir out
          # copy repository contents except Git internals and workflow files
          rsync -av --exclude='.github' --exclude='.git' --exclude='node_modules' --exclude='.gitignore' ./ out/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1